In [1]:
from ultralytics import YOLO
import numpy as np
import pickle

path_to_base_yolo = "/home/edoardo/aiproject/runs/detect/300/weights/best.pt"
model_tuned = YOLO(path_to_base_yolo)

np.random.seed(100)

# Data for Gaussian noise (V0)

In [2]:
results = {}

# Clean dataset
results["clean"] = model_tuned.val(data="wildlife.yaml")

# Noisy dataset
noises = {"gaussian": [0.1, 0.2], "bernoulli": [0.1, 0.3]}
for noise_type in ["gaussian", "bernoulli"]:
    results[noise_type] = dict()
    for noise in noises[noise_type]:
        results[noise_type][noise] = dict()
        for model in ["v0", "v1"]:
            results[noise_type][noise][model] = model_tuned.val(
                data=f"wildlife_{noise_type}_{noise}_{model}.yaml"
            )

with open("results_detection_yolo.pckl", "wb") as file:
    pickle.dump(results, file)

Ultralytics YOLOv8.2.28 🚀 Python-3.10.0 torch-2.3.0+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Ti, 7951MiB)
Model summary (fused): 168 layers, 3006428 parameters, 0 gradients, 8.1 GFLOPs


val: Scanning /home/edoardo/aiproject/datasets/wildlife/valid/labels.cache... 225 images, 0 backgrounds, 0 corrupt: 100%|██████████| 225/225 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   7%|▋         | 1/15 [00:00<00:01,  7.31it/s]/home/edoardo/anaconda3/envs/aiproject/lib/python3.10/site-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv2d(input, weight, bias, self.stride,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 15/15 [00:01<00:00, 12.97it/s]


                   all        225        379      0.942       0.91      0.953      0.827
               buffalo         62         89      0.951      0.899      0.948      0.824
              elephant         53         91      0.909      0.876      0.931      0.802
                 rhino         55         85      0.965      0.963      0.975      0.873
                 zebra         59        114      0.945      0.903      0.959      0.808
Speed: 0.5ms preprocess, 2.8ms inference, 0.0ms loss, 0.3ms postprocess per image
Results saved to runs/detect/val
Ultralytics YOLOv8.2.28 🚀 Python-3.10.0 torch-2.3.0+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Ti, 7951MiB)


val: Scanning /home/edoardo/aiproject/datasets/wildlife_gaussian_0.1_v0/valid/labels... 225 images, 0 backgrounds, 0 corrupt: 100%|██████████| 225/225 [00:00<00:00, 3249.69it/s]

val: New cache created: /home/edoardo/aiproject/datasets/wildlife_gaussian_0.1_v0/valid/labels.cache



                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 15/15 [00:01<00:00, 13.27it/s]


                   all        225        379      0.911      0.746      0.842      0.676
               buffalo         62         89      0.949      0.742      0.876      0.735
              elephant         53         91      0.818      0.741      0.775       0.62
                 rhino         55         85      0.891      0.882      0.931       0.77
                 zebra         59        114      0.986       0.62      0.785      0.581
Speed: 0.5ms preprocess, 1.6ms inference, 0.0ms loss, 0.4ms postprocess per image
Results saved to runs/detect/val2
Ultralytics YOLOv8.2.28 🚀 Python-3.10.0 torch-2.3.0+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Ti, 7951MiB)


val: Scanning /home/edoardo/aiproject/datasets/wildlife_gaussian_0.1_v1/valid/labels... 225 images, 0 backgrounds, 0 corrupt: 100%|██████████| 225/225 [00:00<00:00, 1473.98it/s]

val: New cache created: /home/edoardo/aiproject/datasets/wildlife_gaussian_0.1_v1/valid/labels.cache



                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 15/15 [00:01<00:00, 13.08it/s]


                   all        225        379        0.9       0.75      0.835      0.672
               buffalo         62         89      0.867      0.854      0.893      0.752
              elephant         53         91      0.874      0.637      0.752      0.601
                 rhino         55         85      0.903      0.918      0.939      0.781
                 zebra         59        114      0.958      0.593      0.756      0.554
Speed: 0.6ms preprocess, 1.6ms inference, 0.0ms loss, 0.4ms postprocess per image
Results saved to runs/detect/val3
Ultralytics YOLOv8.2.28 🚀 Python-3.10.0 torch-2.3.0+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Ti, 7951MiB)


val: Scanning /home/edoardo/aiproject/datasets/wildlife_gaussian_0.2_v0/valid/labels... 225 images, 0 backgrounds, 0 corrupt: 100%|██████████| 225/225 [00:00<00:00, 2429.14it/s]

val: New cache created: /home/edoardo/aiproject/datasets/wildlife_gaussian_0.2_v0/valid/labels.cache



                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 15/15 [00:02<00:00,  6.52it/s]


                   all        225        379       0.87      0.693      0.786      0.606
               buffalo         62         89      0.937      0.673      0.798      0.667
              elephant         53         91        0.8      0.648       0.71      0.545
                 rhino         55         85      0.783      0.847      0.868      0.664
                 zebra         59        114      0.958      0.604      0.768      0.548
Speed: 0.6ms preprocess, 1.6ms inference, 0.0ms loss, 0.4ms postprocess per image
Results saved to runs/detect/val4
Ultralytics YOLOv8.2.28 🚀 Python-3.10.0 torch-2.3.0+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Ti, 7951MiB)


val: Scanning /home/edoardo/aiproject/datasets/wildlife_gaussian_0.2_v1/valid/labels... 225 images, 0 backgrounds, 0 corrupt: 100%|██████████| 225/225 [00:00<00:00, 2611.26it/s]

val: New cache created: /home/edoardo/aiproject/datasets/wildlife_gaussian_0.2_v1/valid/labels.cache



                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 15/15 [00:01<00:00, 13.13it/s]


                   all        225        379      0.804      0.617      0.705      0.513
               buffalo         62         89      0.775      0.695       0.77      0.601
              elephant         53         91      0.763      0.532      0.642      0.484
                 rhino         55         85      0.784      0.853       0.86      0.638
                 zebra         59        114      0.894      0.386      0.548      0.329
Speed: 0.6ms preprocess, 1.6ms inference, 0.0ms loss, 0.5ms postprocess per image
Results saved to runs/detect/val5
Ultralytics YOLOv8.2.28 🚀 Python-3.10.0 torch-2.3.0+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Ti, 7951MiB)


val: Scanning /home/edoardo/aiproject/datasets/wildlife_bernoulli_0.1_v0/valid/labels... 225 images, 0 backgrounds, 0 corrupt: 100%|██████████| 225/225 [00:00<00:00, 3469.83it/s]

val: New cache created: /home/edoardo/aiproject/datasets/wildlife_bernoulli_0.1_v0/valid/labels.cache



                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 15/15 [00:01<00:00, 12.36it/s]


                   all        225        379      0.902      0.798      0.884      0.735
               buffalo         62         89        0.8      0.896      0.922      0.758
              elephant         53         91      0.934       0.67       0.83      0.687
                 rhino         55         85      0.941      0.906      0.959      0.826
                 zebra         59        114      0.933      0.719      0.824       0.67
Speed: 0.5ms preprocess, 1.6ms inference, 0.0ms loss, 0.4ms postprocess per image
Results saved to runs/detect/val6
Ultralytics YOLOv8.2.28 🚀 Python-3.10.0 torch-2.3.0+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Ti, 7951MiB)


val: Scanning /home/edoardo/aiproject/datasets/wildlife_bernoulli_0.1_v1/valid/labels... 225 images, 0 backgrounds, 0 corrupt: 100%|██████████| 225/225 [00:00<00:00, 3132.97it/s]

val: New cache created: /home/edoardo/aiproject/datasets/wildlife_bernoulli_0.1_v1/valid/labels.cache



                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   0%|          | 0/15 [00:00<?, ?it/s]

: 

In [5]:
np.set_printoptions(precision=3)
names = results_gaussian_v0[0].names
indexes = results_gaussian_v0[0].ap_class_index  # class indexes
# Clean dataset
matr_cleaned = np.zeros((len(indexes) + 1, 3 * 1))

matr_cleaned[:, 0] = [*results_cleaned.box.p, results_cleaned.box.p.mean()]
matr_cleaned[:, 1] = [*results_cleaned.box.r, results_cleaned.box.r.mean()]
# mAP50-95
mAP50_c = np.array([results_cleaned.box.all_ap[j].mean() for j in indexes])
matr_cleaned[:, 2] = [*mAP50_c, mAP50_c.mean()]
for i, res in enumerate(results_gaussian_v0):
    matr = np.zeros(
        (len(indexes) + 1, 3 * 1)
    )  # matrix that we update with the values to print
    matr[:, 0] = [*res.box.p, res.box.p.mean()]
    matr[:, 1] = [*res.box.r, res.box.r.mean()]
    # mAP50-95
    mAP50 = np.array([res.box.all_ap[j].mean() for j in indexes])
    matr[:, 2] = [*mAP50, mAP50.mean()]

    # For
    res1 = results_gaussian_v1[i]
    matr1 = np.zeros(
        (len(indexes) + 1, 3 * 1)
    )  # matrix that we update with the values to print
    matr1[:, 0] = [*res1.box.p, res1.box.p.mean()]
    matr1[:, 1] = [*res1.box.r, res1.box.r.mean()]
    # mAP50-95
    mAP50_1 = np.array([res1.box.all_ap[j].mean() for j in indexes])
    matr1[:, 2] = [*mAP50_1, mAP50_1.mean()]
    print(np.hstack([matr, matr1]))

[[0.944 0.754 0.724 0.843 0.854 0.752]
 [0.798 0.758 0.63  0.885 0.648 0.606]
 [0.873 0.894 0.762 0.905 0.892 0.776]
 [0.973 0.63  0.582 0.944 0.594 0.546]
 [0.897 0.759 0.675 0.894 0.747 0.67 ]]
[[0.889 0.629 0.661 0.824 0.674 0.603]
 [0.759 0.623 0.533 0.84  0.56  0.482]
 [0.77  0.835 0.656 0.777 0.788 0.624]
 [0.972 0.623 0.56  0.905 0.351 0.325]
 [0.848 0.678 0.602 0.837 0.593 0.508]]


# Results for Gaussian noise (V1)